title: Mayank Vyas # your name (or website title) here
logo: "/profile.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
 Data Scientist
  <br><br>
  <a href="mailto:mayankvyasdks@gmail.com">mayankvyasdks@gmail.com </a>
  <br>
  <a href="https://www.linkedin.com/in/mayank-s-vyas/">LinkedIn Profile</a>
  <br>
  <a href="https://github.com/mayank-s-vyas">Gihub</a> 
theme: jekyll-theme-minimal
